server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

    
  
    hikari:
      keepalive-time: 60000
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      initialization-fail-timeout: 60000

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:20MB}
      max-request-size: ${MAX_REQUEST_SIZE:20MB}

app:
  upload:
    directory: ${UPLOAD_DIR:uploads}
    originals-directory: ${UPLOAD_ORIGINALS_DIR:uploads/originals}

  token:
    expiration: ${TOKEN_EXPIRATION:3600}


debug: true

logging:
  level:
    org.springframework: DEBUG